import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Project: HMS</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <br/><br/><br/><br/>
        <Image
            src="https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/cnoC/image/4yPtuRXtR0-jusOMCCXb4MeN6zU.jpg"
            width={500}
            height={500}
            alt={"cute jordy"}
        />
        <h1 className={styles.title}>
          랜딩페이지 header title
        </h1>

        <form>
          <input id={'mail'} name={'mailForm'} type={'text'} autoComplete={'name'} required />
          <button type={'submit'}>전송</button>
        </form>


        <p className={styles.description}>
          랜딩페이지 sub header title
        </p>

        <br/><br/><br/><br/>

        <h2>우리가 만들제품</h2>
        <Image
          src='https://images.squarespace-cdn.com/content/v1/55b6a6dce4b089e11621d3ed/1585087896250-R3GZ6OFWYQRZUJRCJU3D/produce_monthly.png'
          width={500}
          height={300}
          alt={"cute jordy"}
        />
        <br/><br/>
        <span>제품소개</span>

        <div>
          어쩌구저쩌구 어쩌구저쩌구 <br/>
          어쩌구저쩌구 어쩌구저쩌구 <br/>
        </div>

        <br/><br/><br/><br/>
        <h2>우리의 비전</h2>


        <br/><br/>
        <Image
            src="https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/cnoC/image/4yPtuRXtR0-jusOMCCXb4MeN6zU.jpg"
            width={300}
            height={300}
            alt={"cute jordy"}
        />
        <h3>비전 1번</h3>
        <div>
          어쩌구저쩌구 어쩌구저쩌구 <br/>
          어쩌구저쩌구 어쩌구저쩌구 <br/>
        </div>

        <br/><br/>
        <Image
            src="https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/cnoC/image/4yPtuRXtR0-jusOMCCXb4MeN6zU.jpg"
            width={300}
            height={300}
            alt={"cute jordy"}
        />
        <h3>비전 2번</h3>
        <div>
          어쩌구저쩌구 어쩌구저쩌구 <br/>
          어쩌구저쩌구 어쩌구저쩌구 <br/>
        </div>

        <br/><br/>
        <Image
            src="https://img1.daumcdn.net/thumb/R1280x0.fjpg/?fname=http://t1.daumcdn.net/brunch/service/user/cnoC/image/4yPtuRXtR0-jusOMCCXb4MeN6zU.jpg"
            width={300}
            height={300}
            alt={"cute jordy"}
        />
        <h3>비전 3번</h3>
        <div>
          어쩌구저쩌구 어쩌구저쩌구 <br/>
          어쩌구저쩌구 어쩌구저쩌구 <br/>
        </div>

        <br/><br/><br/><br/>
        <h2>우리의 수상경력</h2>
        <br/><br/>
        <h3>수상경력1번: 1번소개</h3>
        <h3>수상경력1번: 2번소개</h3>
        <h3>수상경력1번: 3번소개</h3>

        <br/><br/><br/><br/>
        <h1>더 보고 싶으시면?</h1>
        <div>여기누르세요~~</div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          PROJECT HMS{" "}, 2021 서울시립대학교 100주년기념관 abc호
        </a>
      </footer>
    </div>
  );
}
